version: "3.8"

services:

  accounts:
    image: aggeles/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - aggeles-network
    
  loans:
    image: aggeles/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - aggeles-network
    
  cards:
    image: aggeles/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - aggeles-network
    
networks:
  aggeles-network: